### ISSUE TITLE
Empty panels are visible

### ISSUE THREAD

**Issue by kayhide** [blueimpact/frame-generator#9]
When scrolling down the top page, empty `Templates`, `ForeGrounds` and `Preview Widget` are visible.

https://gyazo.com/ab621ef2260168c1afa94c89ffaed4e6

Selecting corresponding header menu shows each content properly.

https://gyazo.com/0b799730e63fd35f17752928bf7eb7cc

**Comment by dfordivam** [comment]
This is by design, the user is expected to click the Navigation tab to update the contents of these.
This was actually supposed to be a non-scrollable page, with tabbed widgets, but I kept it this way to keep things simple. Later I will introduce a separate tab for each widget...

**Comment by dfordivam** [comment]
Fixed in v1.2
